import { PolicySchema, InferenceRequestSchema, TraceEventSchema, type Policy } from './index';
// Synthetic contract fixtures only. No fixture is benchmark evidence or a live result.
export const demoPolicy = PolicySchema.parse({ id: 'balanced', version: 1, weights: { quality: .6, cost: .25, latency: .15 }, requestBudgetMicros: 5000000, dailyBudgetMicros: 10000000, maxOutputTokens: 1500, maxLatencyMs: 30000, minimumQuality: .5, allowIncompleteCoverage: false, uncertaintyPenalty: .15, maxCandidates: 5, auctionDeadlineMs: 300, bidVisibility: 'dark', continuity: 'auto', retainPayloads: true });
export const scenarios: { id: string; title: string; prompt: string; emphasis: string; weights: Policy['weights'] }[] = [
  { id: 'support', title: 'Support triage', prompt: 'Classify this ticket and draft a short reply: My invoice shows two charges for the same order.', emphasis: 'Latency · cost', weights: { quality: .2, cost: .4, latency: .4 } },
  { id: 'extraction', title: 'Invoice extraction', prompt: 'Extract invoice number, amount and currency as JSON: Invoice INV-204, total USD 145.00.', emphasis: 'Structured output · accuracy', weights: { quality: .6, cost: .3, latency: .1 } },
  { id: 'coding', title: 'Code debugging', prompt: 'Explain and fix this function: const sum = xs => xs.reduce((a, b) => a + b); It throws on an empty array.', emphasis: 'Coding · reasoning', weights: { quality: .75, cost: .15, latency: .1 } },
  { id: 'research', title: 'Research synthesis', prompt: 'Compare these sources and cite their IDs. [A] Trial latency improved but cost rose. [B] Production latency was unchanged and cost fell. Explain the disagreement without inventing causes.', emphasis: 'Context · evidence', weights: { quality: .75, cost: .1, latency: .15 } },
  { id: 'design', title: 'UI design and prototyping', prompt: 'Create standalone HTML and CSS for a responsive landing page for a neighborhood seed library. Use a clear hierarchy and no JavaScript.', emphasis: 'Frontend · instruction following', weights: { quality: .7, cost: .15, latency: .15 } },
];
export const sampleRequest = InferenceRequestSchema.parse({ policyId: demoPolicy.id, idempotencyKey: 'fixture-request-1', messages: [{ role: 'user', content: scenarios[0]!.prompt }], maxOutputTokens: 1500 });
export const sampleEvents = [TraceEventSchema.parse({ requestId: 'fixture-request-1', sequence: 0, type: 'assessment', assessment: { task: 'support', complexity: 'low', confidence: .8, continuity: 'fresh', continuityConfidence: .8, modelVersion: 'synthetic-fixture', questionVersion: '0.1' } })];
