export interface Participant { id: string; name: string; role: string }
export interface FlowStep { from: string; to: string; label: string; interface: string; detail: string; kind: 'api' | 'internal' | 'simulated'; payload: string }
export interface FlowPhase { id: string; title: string; subtitle: string; participants: Participant[]; steps: FlowStep[] }
export const phases: FlowPhase[] = [
  { id: 'setup', title: 'Configure the market', subtitle: 'A builder defines the region; reviewed evidence determines who can enter it.', participants: [
    { id: 'builder', name: 'App builder', role: 'Policy owner' }, { id: 'advisor', name: 'Advisor model', role: 'MCP client' }, { id: 'vispr', name: 'Vispr', role: 'Control plane' }, { id: 'operator', name: 'Operator', role: 'Catalog reviewer' }, { id: 'provider', name: 'Provider', role: 'Serving endpoint' },
  ], steps: [
    { from: 'builder', to: 'vispr', label: 'Create app + policy', interface: 'POST /api/applications · /api/applications/{id}/keys', detail: 'An invited builder creates the application, its policy and an application key. The policy owns spending limits, latency and quality requirements.', kind: 'api', payload: 'Organization, app name, versioned policy. Builder session required.' },
    { from: 'provider', to: 'vispr', label: 'Register deployment', interface: 'POST /api/providers · /api/providers/{id}/deployments', detail: 'A provider registers a concrete serving option. OpenRouter offerings pin a provider; direct offerings use an operator-approved endpoint. Registration alone does not certify eligibility.', kind: 'api', payload: 'Model identity, capabilities, serving transport and endpoint configuration.' },
    { from: 'operator', to: 'vispr', label: 'Review model evidence', interface: 'Catalog ingestion CLI + reviewed routing publication', detail: 'Public source imports become reviewed, versioned benchmark observations. Endpoint cost and full-completion latency need separate evidence. Missing values stay unknown.', kind: 'internal', payload: 'Catalog snapshot, independent benchmark axes, dated endpoint metrics.' },
    { from: 'builder', to: 'advisor', label: 'Describe invocation', interface: 'Builder’s MCP-capable model client', detail: 'The builder describes a stable invocation source, workload shape and desired tradeoffs. The advisor is the model in that client, not a new inference provider inside this diagram.', kind: 'api', payload: 'For example: invoice.extract, output format, latency and cost ceilings.' },
    { from: 'advisor', to: 'vispr', label: 'Read the option space', interface: 'POST /mcp · get_model_space', detail: 'The advisor reads the authenticated app’s policy and reviewed model evidence, or the labeled discovery snapshot when no reviewed configuration exists.', kind: 'api', payload: 'Application key, optional policy ID. Returns snapshot hash, axes and provenance.' },
    { from: 'advisor', to: 'vispr', label: 'Propose fixed region', interface: 'POST /mcp · propose_static_manifold', detail: 'The model proposes hard latency/cost bands and independent benchmark floors. The endpoint validates the draft against policy. It cannot activate itself or dispatch inference.', kind: 'api', payload: 'Source label, policy version, snapshot hash, token shape, criteria and rationale.' },
    { from: 'builder', to: 'vispr', label: 'Review + publish', interface: 'POST /api/applications/{id}/routing', detail: 'An authorized builder publishes a reviewed catalog and routing config. Approved source criteria stay fixed while qualifying model membership can change. Other source bindings are preserved.', kind: 'api', payload: 'Reviewed catalog + config.sourceRouting + active flag. Activation checks apply.' },
  ] },
  { id: 'inference', title: 'Route an inference call', subtitle: 'Every bid must fit the app’s approved region. A better price cannot erase a failed benchmark floor.', participants: [
    { id: 'app', name: 'Calling app', role: 'Vispr SDK' }, { id: 'vispr', name: 'Vispr', role: 'Routing service' }, { id: 'jev', name: 'Jev', role: 'Task classifier' }, { id: 'bidders', name: 'Bid adapters', role: 'Simulated providers' }, { id: 'provider', name: 'Winner', role: 'Inference endpoint' }, { id: 'ledger', name: 'Supabase', role: 'Atomic state' },
  ], steps: [
    { from: 'app', to: 'vispr', label: 'Submit inference', interface: 'SDK stream() → POST /api/inference/stream', detail: 'The app sends a request with its saved policy and optional stable source label. The OpenAI-compatible alternative is POST /v1/chat/completions.', kind: 'api', payload: 'Bearer app key, messages, policyId, source, output limit and idempotency key.' },
    { from: 'vispr', to: 'ledger', label: 'Reserve spending', interface: 'begin_execution · authorize_classification RPCs', detail: 'Vispr validates the app and reviewed configuration, then reserves a conservative spending allowance before paid work. Daily and request limits still apply.', kind: 'internal', payload: 'App, policy version, request identity and bounded cost allowance.' },
    { from: 'vispr', to: 'jev', label: 'Assess task on cache miss', interface: 'TypeSafe API · batched Jev questions', detail: 'On an exact assessment-cache hit, this remote call is skipped. Otherwise Jev assesses task, complexity and continuity. Static source constraints remain binding either way.', kind: 'api', payload: 'Bounded request context and fixed classification questions. Classification usage is recorded.' },
    { from: 'jev', to: 'vispr', label: 'Return assessment', interface: 'Task assessment + confidence', detail: 'Vispr combines the task profile with the source’s fixed criteria and fresh evidence. Every selected benchmark stays independent. Empty pools fail closed.', kind: 'api', payload: 'Task, complexity, continuity and confidence; cached assessments follow the same selection checks.' },
    { from: 'vispr', to: 'bidders', label: 'Invite eligible options', interface: 'Internal Bidder adapter · dark/workload invitation', detail: 'Only qualifying deployments receive invitations. Dark invitations omit the prompt. Workload mode adds bounded workload metadata; providers do not need the app’s ranking rationale.', kind: 'simulated', payload: 'Auction ID, eligible offering IDs and deadline; optional token buckets.' },
    { from: 'bidders', to: 'vispr', label: 'Submit bounded bids', interface: 'Bidder.bid() · submit_bid RPC', detail: 'The current demo generates simulated bids using provider strategies. Vispr checks cost and latency bands again. Registered endpoint capacity is reserved for participating offerings.', kind: 'simulated', payload: 'Token rates, queue delay, throughput, validity and capacity reservation token.' },
    { from: 'vispr', to: 'ledger', label: 'Award atomically', interface: 'award_auction RPC', detail: 'An atomic award prevents competing winners. Losing capacity reservations are released. No qualifying bid means no inference dispatch.', kind: 'internal', payload: 'Auction ID, winning bid and the application’s persisted request state.' },
    { from: 'vispr', to: 'provider', label: 'Dispatch to winner', interface: 'Pinned OpenRouter /chat/completions or approved direct endpoint', detail: 'The selected endpoint receives the actual inference payload only after award. Hosted open models and verified self-hosted options can participate through their serving deployments.', kind: 'api', payload: 'Messages, tool/output requirements and output limit. Serving identity is pinned.' },
    { from: 'provider', to: 'vispr', label: 'Stream output + usage', interface: 'Provider SSE stream', detail: 'The adapter normalizes output, tool deltas and usage. Missing final cost remains pending reconciliation rather than becoming a fabricated zero charge.', kind: 'api', payload: 'Text/tool deltas, finish reason, token usage, generation and provider identity.' },
    { from: 'vispr', to: 'app', label: 'Deliver answer + trace', interface: 'Native SSE events or OpenAI-compatible stream', detail: 'The app receives the response. The native event protocol also carries assessment, candidates, bids, award and usage so the decision can be inspected.', kind: 'api', payload: 'Sequenced events and a request ID for later trace retrieval.' },
  ] },
  { id: 'operations', title: 'Inspect and reconcile', subtitle: 'Execution charges are real; commercial provider settlement remains future work.', participants: [
    { id: 'app', name: 'App / builder', role: 'Request owner' }, { id: 'vispr', name: 'Vispr', role: 'Execution service' }, { id: 'ledger', name: 'Supabase', role: 'Trace + spend ledger' }, { id: 'provider', name: 'Provider', role: 'Usage source' },
  ], steps: [
    { from: 'vispr', to: 'ledger', label: 'Record events + usage', interface: 'trace_events · finish_execution RPC', detail: 'Vispr persists the decision trail and settles known usage. Uncertain dispatched costs remain reserved for reconciliation. The winning capacity reservation is released at settlement.', kind: 'internal', payload: 'Sequenced decision events, output/usage according to policy, settlement state.' },
    { from: 'app', to: 'vispr', label: 'Inspect the decision', interface: 'SDK trace() → GET /api/requests/{id}', detail: 'The application can retrieve its own persisted trace, including excluded models, auction results and usage. Other applications cannot read this request.', kind: 'api', payload: 'Application key and request ID.' },
    { from: 'vispr', to: 'app', label: 'Return stored trace', interface: 'Trace API + Request trace GUI', detail: 'The UI explains which constraints applied and why a bid won. The explanatory product-flow diagram itself is not a recording of live traffic.', kind: 'api', payload: 'Assessment, candidate evidence, bid/award events and usage status.' },
    { from: 'app', to: 'vispr', label: 'Cancel if still running', interface: 'SDK cancel() → POST /api/requests/{id}/cancel', detail: 'Cancellation is an alternate path, not a required step after completion. It stops further work where possible; already dispatched provider charges may still need reconciliation.', kind: 'api', payload: 'Application-owned request ID and cancellation intent.' },
    { from: 'vispr', to: 'provider', label: 'Resolve uncertain usage', interface: 'Protected maintenance route + provider usage lookup', detail: 'Maintenance reconciles pending usage where the adapter supports it. Retention cleanup and stale reservation checks also run here. Commercial payout/net settlement between counterparties is deferred.', kind: 'api', payload: 'Generation identity and usage evidence; unresolved costs stay pending.' },
  ] },
];
