'use client';
import { useMemo, useState } from 'react';
import { axes, explore, illustrativeModels, sortModels, type Axis, type Benchmark, type ExplorerModel, type EvaluatedModel, type ExplorerBands } from '../../lib/model-explorer';

const benchmarks: Benchmark[] = ['coding', 'reasoning', 'design'];
const defaults: ExplorerBands = { maxCost: .02, maxLatency: 5, benchmarks: { coding: 60, reasoning: 60, design: 55 } };
const format = (axis: Axis, value: number | null) => value === null ? 'Unknown' : axis === 'cost' ? `$${value.toFixed(4)}` : axis === 'latency' ? `${value.toFixed(1)}s` : value.toLocaleString('en-US', { maximumFractionDigits: 1 });
export function ModelExplorer({ discovery, retrievedAt }: { discovery: ExplorerModel[]; retrievedAt: string }) {
  const [dataset, setDataset] = useState<'illustrative' | 'discovery'>('illustrative');
  const [bands, setBands] = useState<ExplorerBands>(defaults);
  const [inputTokens, setInputTokens] = useState(1000), [outputTokens, setOutputTokens] = useState(500);
  const [x, setX] = useState<Axis>('cost'), [y, setY] = useState<Axis>('coding');
  const [sort, setSort] = useState<Axis>('cost'), [selected, setSelected] = useState('balanced');
  const [frontierOnly, setFrontierOnly] = useState(false);
  const [copied, setCopied] = useState('');
  const rows = useMemo(() => explore(dataset === 'illustrative' ? illustrativeModels : discovery, bands, inputTokens, outputTokens), [dataset, discovery, bands, inputTokens, outputTokens]);
  const shown = sortModels(frontierOnly ? rows.filter(r => r.status === 'frontier') : rows, sort);
  const detail = rows.find(r => r.id === selected) ?? rows[0]!;
  const activeBenchmarks = benchmarks.filter(key => bands.benchmarks[key] !== undefined);
  const count = (status: EvaluatedModel['status']) => rows.filter(r => r.status === status).length;
  function reset() { setBands(defaults); setInputTokens(1000); setOutputTokens(500); setFrontierOnly(false); setCopied(''); }
  async function copy() {
    const config = { latencyMs: { max: bands.maxLatency * 1000 }, estimatedCostMicros: { max: Math.round(bands.maxCost * 1e6) }, ...(activeBenchmarks.length ? { benchmarks: activeBenchmarks.map(key => ({ benchmark: `illustrative-${key}`, version: 'demo-v1', minimum: 0, maximum: 100, higherIsBetter: true, minimumNormalizedScore: bands.benchmarks[key]! / 100, weight: 1 })) } : {}) };
    try { await navigator.clipboard.writeText(JSON.stringify(config, null, 2)); setCopied('Copied draft. Replace illustrative benchmark IDs before use.'); }
    catch { setCopied('Clipboard unavailable in this browser.'); }
  }
  return <main className="explorer">
    <div className="explorer__heading"><div><p className="eyebrow">Model selection / Explore the tradeoffs</p><h1>Find the shape of your pool.</h1><p className="muted">Latency, task cost, and every benchmark that matters to the invocation.</p></div><div className="explorer__dataset"><label htmlFor="dataset">Evidence set</label><select id="dataset" className="select" value={dataset} onChange={e => { const next = e.target.value as typeof dataset; setDataset(next); setSelected(next === 'illustrative' ? 'balanced' : discovery[0]!.id); setY(next === 'illustrative' ? 'coding' : 'context'); setFrontierOnly(false); }}><option value="illustrative">Illustrative model space</option><option value="discovery">Sourced model discovery</option></select></div></div>
    <div className="explorer__notice" role="note">{dataset === 'illustrative' ? <><strong>Illustrative data</strong><span>Fictional models and scores demonstrate the selection geometry. No inference is dispatched.</span></> : <><strong>Discovery snapshot · {retrievedAt.slice(0, 10)}</strong><span>Advertised starting prices and context limits. Missing verified benchmark and completion-time evidence stays unknown; these are not auction-ready models.</span></>}</div>
    <div className="explorer__layout">
      <aside className="card explorer__controls" aria-label="Pool bands"><div className="explorer__section-head"><h2>Define the pool</h2><button className="explorer__text-button" onClick={reset}>Reset</button></div><p className="fine">Bands are hard limits. An advantage on one axis cannot cancel a failed limit on another.</p>
        <fieldset><legend>01 / Latency</legend><Range label="Maximum completion time" value={bands.maxLatency} min={.5} max={10} step={.1} display={`${bands.maxLatency.toFixed(1)} seconds`} onChange={value => setBands({ ...bands, maxLatency: value })} /></fieldset>
        <fieldset><legend>02 / Task capacity · cost</legend><Range label="Maximum cost per request" value={bands.maxCost} min={.0005} max={.03} step={.0005} display={`$${bands.maxCost.toFixed(4)}`} onChange={value => setBands({ ...bands, maxCost: value })} /><p className="fine">About {Math.floor(1 / bands.maxCost)} requests / $1 at this ceiling, before other charges.</p><div className="explorer__token-inputs"><TokenInput label="Input tokens" value={inputTokens} onChange={setInputTokens} /><TokenInput label="Output tokens" value={outputTokens} onChange={setOutputTokens} /></div></fieldset>
        <fieldset><legend>03 / Inference ability</legend><p className="fine">Each enabled benchmark is an independent axis. Illustrative scores use a 0–100 scale.</p>{benchmarks.map(key => <div className="explorer__benchmark" key={key}><label><input type="checkbox" checked={bands.benchmarks[key] !== undefined} onChange={e => { const next = { ...bands.benchmarks }; if (e.target.checked) next[key] = 60; else delete next[key]; setBands({ ...bands, benchmarks: next }); }} />{axes[key].label}</label>{bands.benchmarks[key] !== undefined && <Range label={`${axes[key].label} minimum`} value={bands.benchmarks[key]!} min={0} max={100} step={1} display={`≥ ${bands.benchmarks[key]}`} onChange={value => setBands({ ...bands, benchmarks: { ...bands.benchmarks, [key]: value } })} />}</div>)}</fieldset>
        <button className="btn-outline" disabled={dataset !== 'illustrative'} onClick={copy}>Copy illustrative criteria</button><p className="fine" role="status">{copied || 'A local exploration draft. Saving application policies is not connected.'}</p>
      </aside>
      <section className="explorer__results" aria-label="Model space">
        <div className="explorer__counts" aria-live="polite"><div><strong>{rows.length}</strong><span>models in view</span></div><div><strong>{count('frontier')}</strong><span>on the frontier</span></div><div><strong>{count('dominated')}</strong><span>dominated</span></div><div><strong>{count('excluded')}</strong><span>outside bands / unknown</span></div></div>
        <div className="card explorer__plot-card"><div className="explorer__section-head"><div><h2>A projection of {activeBenchmarks.length + 2} dimensions</h2><p className="fine">The plot shows two axes. Frontier decisions use all enabled benchmarks, cost, and latency.</p></div><div className="explorer__axis-selects"><AxisSelect label="X axis" value={x} onChange={setX} /><AxisSelect label="Y axis" value={y} onChange={setY} /></div></div>
          <Scatter rows={rows} x={x} y={y} selected={detail.id} onSelect={setSelected} bands={bands} />
          <div className="explorer__legend"><span><i className="frontier" />Frontier</span><span><i className="dominated" />Dominated</span><span><i className="excluded" />Outside bands / unknown</span></div>
        </div>
        <div className="card explorer__table-card"><div className="explorer__section-head"><h2>Every axis, side by side</h2><label><input type="checkbox" checked={frontierOnly} onChange={e => setFrontierOnly(e.target.checked)} /> Frontier only</label></div><div className="explorer__table-scroll"><table className="table"><thead><tr><th>Model</th>{(['cost', 'latency', ...activeBenchmarks] as Axis[]).map(axis => <th key={axis} aria-sort={sort === axis ? axes[axis].better === 'lower' ? 'ascending' : 'descending' : 'none'}><button onClick={() => setSort(axis)}>{axes[axis].label} {sort === axis ? axes[axis].better === 'lower' ? '↑' : '↓' : ''}</button></th>)}<th>Pool status</th></tr></thead><tbody>{shown.map(row => <tr key={row.id} data-selected={detail.id === row.id}><td><button className="explorer__model-button" onClick={() => setSelected(row.id)} aria-pressed={detail.id === row.id}>{row.name}</button><small>{row.provider}</small></td>{(['cost', 'latency', ...activeBenchmarks] as Axis[]).map(axis => <td className="mono" key={axis}>{format(axis, row[axis])}</td>)}<td><span className={`explorer__status ${row.status}`}>{row.status === 'excluded' ? 'Outside / unknown' : row.status === 'frontier' ? 'Frontier' : 'Dominated'}</span></td></tr>)}</tbody></table>{!shown.length && <p className="explorer__empty">No models satisfy this view. Widen the bands or turn off “Frontier only” to inspect exclusions.</p>}</div></div>
        <div className="card explorer__detail"><div><p className="eyebrow">Selected model</p><h2>{detail.name}</h2><p className="fine">{detail.provenance} {detail.sourceUrl && <a href={detail.sourceUrl} target="_blank" rel="noreferrer">View source ↗</a>}</p></div><div><h3>{detail.status === 'frontier' ? 'Why it remains in the pool' : detail.status === 'dominated' ? 'Why it is dominated' : 'Why it is outside the pool'}</h3>{detail.reasons.length ? <ul>{detail.reasons.map(reason => <li key={reason}>{reason}</li>)}</ul> : detail.dominatedBy.length ? <p>{detail.dominatedBy.join(', ')} {detail.dominatedBy.length === 1 ? 'is' : 'are'} no worse on every enabled axis and better on at least one.</p> : <p>Meets every band. No other eligible model is better or equal on all enabled axes and strictly better on one. A stronger benchmark may trade off against cost or latency.</p>}</div></div>
        <p className="fine">This is pool exploration, not an award. Weighted preferences, pool-size limits, current budget, capabilities, and provider bids still determine the final route.</p>
      </section>
    </div>
  </main>;
}
function Range({ label, value, min, max, step, display, onChange }: { label: string; value: number; min: number; max: number; step: number; display: string; onChange(value: number): void }) { return <label className="explorer__range"><span>{label}<strong className="mono">{display}</strong></span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(Number(e.target.value))} /></label>; }
function TokenInput({ label, value, onChange }: { label: string; value: number; onChange(value: number): void }) { return <label>{label}<input type="number" min="0" max="1000000" step="100" value={value} onChange={e => { const n = Number(e.target.value); if (Number.isSafeInteger(n) && n >= 0 && n <= 1000000) onChange(n); }} /></label>; }
function AxisSelect({ label, value, onChange }: { label: string; value: Axis; onChange(value: Axis): void }) { return <label>{label}<select className="select" value={value} onChange={e => onChange(e.target.value as Axis)}>{(Object.keys(axes) as Axis[]).map(axis => <option value={axis} key={axis}>{axes[axis].label}</option>)}</select></label>; }
function Scatter({ rows, x, y, selected, onSelect, bands }: { rows: EvaluatedModel[]; x: Axis; y: Axis; selected: string; onSelect(id: string): void; bands: ExplorerBands }) {
  const points = rows.filter(row => row[x] !== null && row[y] !== null);
  const xmax = benchmarks.includes(x as Benchmark) ? 100 : Math.max(...points.map(row => row[x]!), 0.001) * 1.15, ymax = benchmarks.includes(y as Benchmark) ? 100 : Math.max(...points.map(row => row[y]!), 0.001) * 1.15;
  const px = (n: number) => 80 + n / xmax * 630, py = (n: number) => 310 - n / ymax * 265;
  const bound = (axis: Axis) => axis === 'cost' ? bands.maxCost : axis === 'latency' ? bands.maxLatency : axis === 'context' ? undefined : bands.benchmarks[axis];
  const xb = bound(x), yb = bound(y);
  return <div className="explorer__chart"><svg viewBox="0 0 800 370" role="group" aria-label={`${axes[y].label} by ${axes[x].label}; select a model point or use the table below`}>
    {[0, .25, .5, .75, 1].map(t => <g key={t}><line x1="80" x2="710" y1={py(t * ymax)} y2={py(t * ymax)} stroke="var(--line-soft)" /><text x="70" y={py(t * ymax) + 4} textAnchor="end">{format(y, t * ymax)}</text><text x={px(t * xmax)} y="332" textAnchor="middle">{format(x, t * xmax)}</text></g>)}
    {xb !== undefined && xb <= xmax && <line x1={px(xb)} x2={px(xb)} y1="45" y2="310" className="explorer__band-line"><title>X-axis band boundary</title></line>}{yb !== undefined && yb <= ymax && <line x1="80" x2="710" y1={py(yb)} y2={py(yb)} className="explorer__band-line"><title>Y-axis band boundary</title></line>}
    <text x="395" y="360" textAnchor="middle">{axes[x].label} · {axes[x].unit} · {axes[x].better} is better</text><text x="80" y="22">{axes[y].label} · {axes[y].unit} · {axes[y].better} is better</text>
    {points.map(row => <g key={row.id} role="button" tabIndex={0} aria-label={`Inspect ${row.name}, ${row.status}`} aria-pressed={row.id === selected} onClick={() => onSelect(row.id)} onKeyDown={e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); onSelect(row.id); } }} className={`explorer__point ${row.status}`}><title>{`${row.name}: ${format(x, row[x])}, ${format(y, row[y])}`}</title><circle cx={px(row[x]!)} cy={py(row[y]!)} r={row.id === selected ? 10 : 7} stroke={row.id === selected ? 'var(--ink)' : 'white'} strokeWidth="2" />{(row.name.length <= 12 || row.id === selected) && <text x={px(row[x]!) + 12} y={py(row[y]!) - 10}>{row.name.length > 23 ? row.name.slice(0, 21) + '…' : row.name}</text>}</g>)}
    {!points.length && <text x="395" y="180" textAnchor="middle">No models have values on both selected axes.</text>}
  </svg><p className="fine">{rows.length - points.length} models omitted for unknown coordinates. Dashed lines show band boundaries. Use the table for overlapping points.</p></div>;
}
